---
- secret:
    name: SECRET_OPENSTACK_IMAGE_MANAGER
    data:
      CLOUDS: !encrypted/pkcs1-oaep
        - LffnVb8+3O07qmDvnLP2fvzuTwHBg++m2mfw6YJZNAXiFiHzsKEXWGxAknY3Vmzhb2mvY
          Isp//o5gdwZ/mWRoQjrP1hyTX2INPgruwOwC67YACkAKUqAaaYsuHl9oCVCxKlbcP7k1m
          416ANG3+l91kC9xuOAEJb1jOqvLsFl9RbKzBgb0QfWcZ5phAherZfaJN0dFz7X4DnTVyy
          6H7Cglpedw8nN6QG0umFzWABqxW2wPPupLd77dLtXU2m2Wm0NIpdMx2R9+mSdh370I1ue
          lPuVf/qTSBvPI19YHI3ve9PuAi2Vr4sgLU3uf6+M1KOaHaCMNq/v0qTsPfn4TIPLW1MDZ
          R1RSOD+Uo4cCfekGsaRhagA2j77B1ERjqdnGI9aoMbVwMVnKzKlAJfPxMPsmCNXtkCDSH
          Q+w7nP32E7olDYr6ahN/XDSdGJquq/UDyz/J2m/89nj9KXIQRTcr4hjvaQb34l7qk1wH3
          cZ5nX/UmBYd5+e8y48jKKAHZMV81PGbyE9Az+MKJLMaKO4DT5P4kEGMEPmGEveTzcG2nh
          yAU/TbgmxtRUmOr9YZUoXr1bT5BPd3h+QLpQBG2OTBhNH7LNT3IJ6Ce1Tjbh7nzupDXEE
          V4+C8M1SyCIJsoudTUSuqFRqOrN4cNVVEgHVo8JOhp0q/rv15wYuDzM42lMUXw=
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - W1KDWzWV32Z8rfF2jNk0qngHUhxik3X5kwRouZn0RVosB+xJDtTEiewGO6xrhlZSNz9VU
          ej5L69fvjq08uKWLluJkUl8lYqurhW3CNeTKnC23IewtFtQMcgJdRxY8jrkYljZNummzH
          0PhcqqNaBxZn0LdjPglkWUXDY/2zQDfP/gqo47vQbAzaAdP1qjSQQ2O/WIrIkauWkmFd+
          wB8ACYgtU6j36Z0ChhwZCgov1JSr/ctDfvdDek0q6Rz7FcIWD5YEbCTWDQ0YKjTB7CO/H
          zzMPmHXl8gAWMHqVQugyNCMm0tTaaSrMgntCP/z26nBJ3/sH6xK1lDE04ff7Fklybj2gw
          3fWgQ/85yyDJOTs0fRjxZTzJ2aRGxscGOZWRGn+EjySY2YW+YHDLl6tptXKE0usk5pzOA
          +UlT43tsOGb6M/Tw3rMSYXfU+gPV9rOi5smKCtPctpvq47tnIg0JvsCpZHhXGeOrTpTeO
          oshp6DEYnGFuCLmCP6Y+4lq3VMb/P8cCGG6jXqku8Z4IMKtFYlkcvWG/1iTZYF8A5rEik
          DKb4ZLjYOea2qIPRdstulQY3skPw+2oj4Lm61Ds9qKKdcJ0UC9MsoONBV/1KTlTKGfKHp
          +r1idUwVrTjvk8eJ55P2mW00A+Ecs5aYX9rYd2chVHKlx/6IsSF/elDIh+6S4o=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - bqqJvV+51zBp4WDxrKyO23EvwhnOWuyDAPoHrJ3vXX1k97nIhk/Nsnxwdeos8Iw9j3Vpa
          NglXfKZ2939q4yT3GotUNz7Bh8hMbxZOfsx0bsO7zCcB6k03sJHL5jQjyRKY8vTdU8Y6o
          pwr8jRaBGdE/gnLeg80U0H5yisxYhpeqLWli16HiiDSRgm/0srG5faPJqgEbzbFZ+AMhn
          dME4Mmv/JN8fHsT9iPyZsv98esSPks84TB+I0caqBWzYXfrr30dtEDnyA7KCpRmv4CvF5
          //HVldJa1a6pktdJCO0ushnJdX4CRI2W9JGJr8SQDp3GrQMogWncRS9K38GARixMoTo3i
          DzvBgEtlqUlw8f6zAYoxLeRxV7doSquhBOeS7aBXNb2nN7edEEXPjEUfbUBoRscBlGN9U
          77FaymJY6SJ77DXXcJTmYIoPPyrv6rECbYZsJTVLkbDDInI+fgI1ftQYom6EUTJJTt94Y
          uPbtONYM+KsUZLJepB9vFISaKrh4kOPZiEr4h94tepBosNatEwI1n7m7kfHFONJ+3rVzA
          JMIed4v23rKBKJF51nQd75LlMn1YDoLPD48WKaQ/UDndyDsPKtipocegI+xixcuFmYgyh
          vAM4jdXy/DElDQRvUcI8QA8KcPlZGIz5bYZalF2ipyrnfM4Bl4tcyngduEtHBc=

- semaphore:
    name: semaphore-openstack-image-manager-real-world
    max: 1

- semaphore:
    name: semaphore-openstack-image-manager-mirror-images
    max: 1

- job:
    name: openstack-image-manager-integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- job:
    name: openstack-image-manager-real-world
    semaphores:
      - name: semaphore-openstack-image-manager-real-world
    pre-run: playbooks/pre-real-world.yml
    run: playbooks/real-world.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_IMAGE_MANAGER

- job:
    name: openstack-image-manager-mirror-images
    semaphores:
      - name: semaphore-openstack-image-manager-mirror-images
    pre-run: playbooks/pre-mirror-images.yml
    run: playbooks/mirror-images.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_IMAGE_MANAGER

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
    post:
      jobs:
        - openstack-image-manager-real-world
        - openstack-image-manager-mirror-images
    periodic-daily:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
