---
- job:
    name: openstack-image-manager-integration-test
    nodeset: ubuntu-noble
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    # The deployment of Devstack can take more time than our default timeout.
    timeout: 7200
    roles:
      - zuul: osism/zuul-jobs
        name: devstack
    irrelevant-files:
      - .github/renovate.json
      - .github/workflows/*
      - etc/images/*

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8:
            nodeset: ubuntu-noble
        - mypy:
            nodeset: ubuntu-noble
        - openstack-image-manager-integration-test
        - python-black:
            nodeset: ubuntu-noble
        - tox:
            nodeset: ubuntu-noble
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint:
            nodeset: ubuntu-noble
    periodic-daily:
      jobs:
        - flake8:
            nodeset: ubuntu-noble
        - mypy:
            nodeset: ubuntu-noble
        - openstack-image-manager-integration-test
        - python-black:
            nodeset: ubuntu-noble
        - tox:
            nodeset: ubuntu-noble
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint:
            nodeset: ubuntu-noble
