---
- project:
    default-branch: main
    vars:
      sphinx_source_dir: documentation/source
      sphinx_build_dir: documentation/build
    check:
      jobs:
        - build-sphinx-docs
    gate:
      jobs:
        - build-sphinx-docs
    post:
      jobs:
        - osism-publish-tox-docs-production
