---
- job:
    name: integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - integration-test
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - integration-test
        - yamllint
