---
- secret:
    name: SECRET_OPENSTACK_IMAGE_MANAGER
    data:
      ACCESS_KEY: !encrypted/pkcs1-oaep
        - DyOidBiQrhtAefo1bqpN/hrNWRGdqRezg7rpwAbQIjjQrp9g9+vPMp6gM5X3w7Hao5CUB
          xrlE0M51+LW9o+xXh6MPpx707a0wmfv9T4XsiRS0aDnpx0mKnYWjOHtoFu7u0z0ZcJ/Rv
          CHXmGOQp13t5yEyBV5sZiyiidu1CbCN9q5SUmmNXEUKQ8JwnNoupTlj+qSRMbeaTeDs2/
          NxHoPrvizF/zCpBMKYgEix2d6PldHhx5ZtMtdOQbxCiUZwUxdQjSElI6jvHcT0Kk26omv
          /plba2Q5v2NYaUplsdHB9EQ8sM1oGbivBt59TVxyoiPrHOgDbkb+J7ZBemshJGWKDrgKb
          VCYQC89rf5BJK9/xPrjD7sLlkp5KyD0fIPC7cevVuTZv8FTzvrlVR1jBtD6U7tCTKwKFZ
          vPP3wCxScb4mlcUW5s5nDekyVtMyM6i1GhNYlD4nwFDyqiniW/wCPHELyU0aHVk3q/ZB/
          3vvWVE/PFhSc45z5juEzeYQvkrchExJ2/wd/mj7QrtAFcGfkvaY8P3CmZdh2X0VWxxjQD
          +RXr/yO7gMTBYDpQMapijgC0veWc6SIfOO7/T1emIFWwYrxFaT7h3lzgpuGmWxTe6dKEq
          C8fx39Mpy1ntPcIZ0klJxy1EzhLOswow+uAXnI1oliQTtdBuxhJ/xhU/DV9kJg=
      SECRET_KEY: !encrypted/pkcs1-oaep
        - XzpF0BT5x97af4RxC16cDmuDUiSpLiplcGCulDZ2rNwHez9glhi7/lQXhKWWgD2rnNM86
          nZ1IOFOrovUUFti3Qhx0gy5fS4g5QtQWxGDj5A0auywInwxLdnLEjpaAkbygdmYHBq2h/
          W+7vwpcbLRtQHwQX3RL7wEQ/coMZSahYJ2MGK4AJjUahzPZHq/EgWRwjKqZGbkoQX69Kc
          xkFSoI+6sRKAGm2wI2yTOPFyCEhfGRb5XdbM9ZQPpMpCdpQzYkcx/DoEQygRaekyZzjTU
          RT5uYEfX4EFe9AW26X54lIA82L3ozdkXiRZBA+lNBu/tuPl6DTdVVb+1A89wOfd3q/eWa
          CjoB9AjcP7qxmioNH5Qr/38DyDLZuQ6xVJmSFEwrybjdjfzYAg1fiS3t920ww5E43CxZ+
          jyEnIV8pWaDq/hU+A5EmAHslssDwdZIX8zeZ9keq4UYt8gxFiNSf+KaNeuEcfKwvG/VSJ
          Lp/xKK1F0WbngkCsGH7ehz0VY5M2nfiqxIVGP3hEnIlJsM/YPUnfdKDHvpGmSVpBzHoyo
          Lbs9ps1n1W3HAma7K541oTFPesZiEC9Xv1/ROw1Y5fEWm4i1/JRXMYFwWBmnltysezk1B
          b/pGFRzygcXh3buMfwNmIql5N14szFeHe05bGJyCgps07+xVB+R2lXAN0XEWEc=

- semaphore:
    name: semaphore-openstack-image-manager-mirror-images
    max: 1

- job:
    name: openstack-image-manager-integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- job:
    name: openstack-image-manager-mirror-images
    semaphores:
      - name: semaphore-openstack-image-manager-mirror-images
    pre-run: playbooks/pre-mirror-images.yml
    run: playbooks/mirror-images.yml
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_IMAGE_MANAGER

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
    post:
      jobs:
        - openstack-image-manager-mirror-images
    periodic-daily:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
