---
- job:
    name: real-world-test
    pre-run: playbooks/pre-real-world-test.yml
    run: playbooks/real-world-test.yml
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - real-world-test
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - real-world-test
        - yamllint
