---
- job:
    name: openstack-image-manager-integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    # The deployment of Devstack can take more time than our default timeout.
    timeout: 7200
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
    periodic-daily:
      jobs:
        - flake8
        - hadolint
        - mypy
        - openstack-image-manager-integration-test
        - python-black
        - tox:
            vars:
              tox_envlist: test
              tox_extra_args: -- test/unit
        - yamllint
