---
- secret:
    name: CLOUDS
    data:
      clouds: !encrypted/pkcs1-oaep
        - qwPpXLe8TvNXdmD+wFgUN4X50QTguUzmSAZzGLltKjYTohyPAwcRl9e4RVG6mA6DCl076
          IhKlo42cGJxtrmc5MwTvM5o49u+1d1QeFOV49Mgr0BhgwZUKOjV+KR6QI06mb0FT46yV8
          qGEjICZlayxkNXxGX19UXPLJsqfjPmwic8lCUcorL86xkZ9hy9l+gJGtSSc/s835rVc39
          HNAECpMYt4CndkWbMLjtpPtzdI21ta2CHxan3qfCByD6Dj3Rmw2tzMDbPTcELMJu0bHVg
          S+uw+4FsXsvtfAJsx28j03rhMS6nhMIByKoq+0hkicflfoC35IkX4xVDNuCPsS+5/Ejvb
          LSkoKxwszFhZ35YQ3+7oubjDv3G0rooVE/5dAwbHJXJT7z4ODxu2Iybo7UR6h5G12DxRy
          A7iv+vxCdVb4NNEgxPWDtQiQt92Efez3CaKV+Jbo0JrKd8jh1JlF+xCDqwcIvuIYAeNkp
          xaMto+JdxinwrJe6xrEb68q3EpDGiogPJz5dsKn9c+18TebHKzfWqtI+PiuXbsdYFuQmA
          EaPGzd8z2VJXkH9dre9yN5bKCOnBaoqqpRmrs6Nsx/UukvKW3FxMZM7CsZqL1MTPcQC0n
          8vLRpo7w76bnCTvlftHEd6v6AXZiLTyRtQTemj3XL7LpOnfF1D1k4fay8+B+aY=

- job:
    name: integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- job:
    name: real-world
    pre-run: playbooks/pre-real-world.yml
    run: playbooks/real-world.yml
    secrets:
      - name: clouds
        secret: CLOUDS

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - integration-test
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - integration-test
        - yamllint
    post:
      jobs:
        - real-world
