---
- secret:
    name: CLOUDS
    data:
      clouds: !encrypted/pkcs1-oaep
        - HQP2nZlzp8Z2usmjM2mrAleCBAnMiUDMbo66kkpKfZRgUSTm2BC4R8LQTkOi1O1p2GlwS
          E0DEzgRzFXs4aMrLbx8jCt8eG/mxq2cx1qFEhRTM7ybISgDcxeu+zocXzOt3S8ByuwNFy
          7oWE+m0BePgo4TCDZxbmEH7Nz5T3hLSCfHSi8Yzj08h+lK67EuVbBeLiykavaCBcbQ+yZ
          PB2AttZk1/2ev9zSxrW33EZERR8d91M90bMHodeopAOU9Xxq+cI6gddCbHSAJ/Qdqehlk
          7xDIr2+S55jgr2Y0+/I4jzcFekIzk7jI3SAukrYhZr9/gXLqOp96Ezq0y2t88vV/9uHF3
          3s1oPTWBrfKo7B06PKeFQB8G7e/JSiNahMYKtOhLpxofvqU7nwze6kgkzxPve1IjC64Hz
          kl/wON3UGZo4YBSBaBuV64+OcH3qnT2T0wo2Lgs5+gulRoD8cF/wW8ekrkQLw6/Yxbd4i
          CpjRgIpR37/anrcIL6yGH7lxkk4I2FhQiS//zXF6pLEQZfEeoC/f8/2sISy0FLUanCaY6
          z2BaYIYTfv2lqPOm8gNO+zcmUz+56J1ip1+gAdl9WiAJHMe5X4fEpMT4a0vs07VzQubOO
          S92+1rLeX0xPWAU1LjcgJOFEPb4EYhgwf2AzBO28H3sD3CRh50kV2omA94Al/E=

- job:
    name: integration-test
    pre-run: playbooks/pre-integration-test.yml
    run: playbooks/integration-test.yml
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- job:
    name: real-world
    pre-run: playbooks/pre-real-world.yml
    run: playbooks/real-world.yml
    secrets:
      - name: clouds
        secret: CLOUDS

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - integration-test
        - yamllint
    gate:
      jobs:
        - flake8
        - hadolint
        - markdownlint
        - integration-test
        - yamllint
    post:
      jobs:
        - real-world
