---
- project:
    default-branch: main
    check:
      jobs:
        - build-sphinx-docs
        - markdownlint
    gate:
      jobs:
        - build-sphinx-docs
    post:
      jobs:
        - osism-publish-tox-docs-production
