---
- name: Run preparations
  hosts: all

  roles:
    - ensure-pip

  tasks:
    - name: Run pre script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export PATH=$PATH:$HOME/.local/bin

          pip3 install pipenv
          pipenv install
