---
- name: Pre integration test play
  hosts: all

  vars:
    zuul_work_dir: "{{ zuul.project.src_dir }}"

  roles:
    - role: ensure-tox
    - role: devstack

  tasks:
    - name: Copy clouds.yml configuration file
      ansible.builtin.copy:
        src: "{{ zuul_work_dir }}/.clouds.yml"
        dest: "{{ zuul_work_dir }}/clouds.yml"
        remote_src: true
        mode: '0644'
        owner: zuul
        group: zuul
