---
name: Mirror images (dry run)

"on":
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/mirror-images-dry-run.yml
      - etc/images/*.yml
      - openstack_image_manager/mirror.py

jobs:
  mirror-images-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install tox
      - run: tox -e mirror -- --dry-run
        if: |
          github.repository == 'osism/openstack-image-manager'
