---
name: Run unit tests

"on":
  push:
    paths:
      - openstack_image_manager/**
      - test/**
      - .github/workflows/run-unit-tests.yml
      - requirements.txt
      - tox.ini
    branches:
      - main
  pull_request:
    paths:
      - openstack_image_manager/**
      - test/**
      - .github/workflows/run-unit-tests.yml
      - requirements.txt
      - tox.ini

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install tox
      - run: tox -e test -- test/unit
