---
name: Run integration tests

"on":
  push:
    paths:
      - src/**
      - test/**
      - .github/workflows/run-integration-tests.yml
      - requirements.txt
      - tox.ini
    branches:
      - main
  pull_request:
    paths:
      - src/**
      - test/**
      - .github/workflows/run-integration-tests.yml
      - requirements.txt
      - tox.ini

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: osism/openstack-action@main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install tox
      - run: tox -e test -- test/integration
        env:
          OS_CLIENT_CONFIG_FILE: .github/clouds.yml
